version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "8001:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker1
      KAFKA_ADVERTISED_PORT: 8001
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_offsets_topic_replication_factor: 3
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock/101
    container_name: broker1

  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "8002:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker2
      KAFKA_ADVERTISED_PORT: 8002
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 102
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_offsets_topic_replication_factor: 3
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock/102
    container_name: broker2

  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "8003:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker3
      KAFKA_ADVERTISED_PORT: 8003
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 103
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_offsets_topic_replication_factor: 3
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock/103
    container_name: broker3
